/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\LandingPageMap.glb --transform 
Files: .\LandingPageMap.glb [10.82MB] > E:\VSCode\Personal_Projects\PortfolioPage\public\models\LandingPageMap-transformed.glb [191.08KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LandingPageMap-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EXPORT_GOOGLE_SAT_WM001.geometry} material={materials['rastMat.003']} />
    </group>
  )
}

useGLTF.preload('/LandingPageMap-transformed.glb')
